local Products = {
	{
		ProductId = 3606607266,
		Name = "500 Coins",
		Description = "Add 500 coins to your wallet",
		PriceRobux = 99,
		PriceCoins = 0,
		Rewards = { Coins = 500 },
		Icon = "💵",
	},
	{
		ProductId = 3606607214,
		Name = "1500 Coins",
		Description = "Add 1500 coins to your wallet",
		PriceRobux = 299,
		PriceCoins = 0,
		Rewards = { Coins = 1500 },
		Icon = "💵",
	},
	{
		ProductId = 3606607284,
		Name = "5000 Coins",
		Description = "Add 5000 coins to your wallet",
		PriceRobux = 999,
		PriceCoins = 0,
		Rewards = { Coins = 5000 },
		Icon = "💵",
	},
}

return Products
