--!strict

local PlayerLevels = {
    { level = 1, cost = 0, multiplier = 1.0 },
    { level = 2, cost = 200, multiplier = 1.2 },
    { level = 3, cost = 500, multiplier = 1.4 },
    { level = 4, cost = 1000, multiplier = 1.6 },
    { level = 5, cost = 2000, multiplier = 1.8 },
    { level = 6, cost = 3500, multiplier = 2.0 },
    { level = 7, cost = 5500, multiplier = 2.2 },
    { level = 8, cost = 8000, multiplier = 2.5 },
    { level = 9, cost = 11000, multiplier = 2.8 },
    { level = 10, cost = 15000, multiplier = 3.0 },
}

return PlayerLevels
